import Head from "next/head";
import { ArrowLeft, ShieldCheck, Info } from "lucide-react";
import PremiumLogo from "../components/PremiumLogo";

export default function TermsAndConditions() {
  return (
    <>
      <Head>
        <title>AURORA — Terms &amp; Conditions</title>
        <meta name="description" content="Terms of Service and legal disclaimer for AURORA Investment Research Suite." />
      </Head>

      <div className="relative min-h-screen bg-[#050608] text-white flex flex-col">
        <div className="noise-overlay" />
        <div className="moving-grid" />

        {/* Top Header */}
        <nav className="relative z-10 border-b border-white/5 bg-[#050608]/90 backdrop-blur-md sticky top-0">
          <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
            <div className="flex items-center gap-3">
              <PremiumLogo />
              <span className="hidden md:inline h-4 w-px bg-white/10" />
              <span className="text-xs text-[#98A2B3]">Legal Framework</span>
            </div>
            <a
              href="/"
              className="flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.02] pl-3.5 pr-5 py-2 text-[10px] uppercase text-[#98A2B3] hover:text-white transition hover:border-[#FF4B2B]"
            >
              <ArrowLeft className="h-3.5 w-3.5" />
              <span className="tracking-[0.15em]">Back to Home</span>
            </a>
          </div>
        </nav>

        {/* Content */}
        <main className="relative z-10 mx-auto max-w-3xl px-6 py-16 flex-1 space-y-10">
          
          <div className="space-y-4">
            <div className="inline-flex items-center gap-2 rounded-full border border-[#FF4B2B]/20 bg-[#FF4B2B]/5 px-3.5 py-1.5 text-[9px] uppercase tracking-wider text-[#FF7A3D]">
              <ShieldCheck className="h-3.5 w-3.5" />
              AURORA USER AGREEMENT
            </div>
            <h1 className="text-4xl font-extrabold tracking-tight md:text-5xl bg-gradient-to-r from-white via-white to-[#FF7A3D] bg-clip-text text-transparent">
              Terms &amp; Conditions
            </h1>
            <p className="text-xs text-[#98A2B3] leading-relaxed">
              Last Updated: July 2026. Please read this agreement carefully before utilizing our investment audit workspaces.
            </p>
          </div>

          <div className="space-y-6 text-sm text-[#98A2B3] leading-relaxed">
            
            <section className="space-y-2 border-l border-white/5 pl-4">
              <h3 className="font-bold text-white uppercase tracking-wider text-xs">1. Scope of Service</h3>
              <p>
                AURORA provides autonomous equity audits, news compiling, and structured financial summaries by crawling public datasets and applying Google Gemini model filters. The outputs generated by the suite are designed for research assistance and evaluation purposes only.
              </p>
            </section>

            <section className="space-y-2 border-l border-white/5 pl-4">
              <h3 className="font-bold text-white uppercase tracking-wider text-xs">2. Financial Message &amp; Report Consent</h3>
              <p>
                By creating an account, you consent to allow the platform to execute automated scans and scrape public financial indicators matching your stock queries. All news data parsed for report grounding is collected from standard feeds on-demand in-memory.
              </p>
            </section>

            <section className="space-y-2 border-l border-white/5 pl-4">
              <h3 className="font-bold text-white uppercase tracking-wider text-xs">3. Investment Disclaimers</h3>
              <p>
                AURORA does **not** provide professional financial advice, licensing recommendations, or broker services. Investment results and ratings are derived algorithmically. Users accept complete responsibility for executing trades or matching investment compliance rules based on their selected risk settings.
              </p>
            </section>

            <section className="space-y-2 border-l border-white/5 pl-4">
              <h3 className="font-bold text-white uppercase tracking-wider text-xs">4. Guest Session Limitations</h3>
              <p>
                Guest User Mode operates as a local session. In Guest Mode, search items, risk selection data, and parsed reports are held strictly in-memory and will be cleared when you exit your browser tab or close the session. No data from guest searches is stored in our database.
              </p>
            </section>

          </div>

          {/* Premium Disclaimer Info Box */}
          <div className="rounded-xl border border-[#FF4B2B]/20 bg-[#FF4B2B]/5 p-5 flex items-start gap-3.5">
            <Info className="h-5 w-5 text-[#FF7A3D] shrink-0 mt-0.5" />
            <div className="space-y-1.5">
              <h4 className="text-xs font-bold text-white uppercase tracking-wider">Regulatory Compliance Note</h4>
              <p className="text-xs text-[#98A2B3] leading-relaxed">
                All data scraped from public quote providers operates under standard fair-use agreements. AURORA is not affiliated with nor endorsed by the listed companies or indices scanned in the workspace.
              </p>
            </div>
          </div>

        </main>
      </div>
    </>
  );
}
